services:
  hysteria2:
    container_name: hysteria2
    cap_add:
      - NET_ADMIN
    command: server -c /etc/hysteria2.yaml
    image: tobyxdd/hysteria:v2
    networks:
      - wgnet
    ports:
      - "${HYSTERIA2_HTTP_PORT}:80"
      - "${HYSTERIA2_HTTPS_PORT}:443"
    restart: always
    volumes:
      - ./acme:/acme
      - ./hysteria2.yaml:/etc/hysteria2.yaml:ro

  wireguard:
    container_name: wireguard
    depends_on:
      - hysteria2
    cap_add:
      - NET_ADMIN
    image: linuxserver/wireguard:latest
    networks:
      - wgnet
    ports:
      - "${SERVERPORT}:${SERVERPORT}/udp"
    restart: always
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ./wireguard/config:/config

  wireguard-ui:
    container_name: wireguard-ui
    depends_on:
      - wireguard
    expose:
      - "5000/tcp"
    image: ngoduykhanh/wireguard-ui:latest
    networks:
      - wgnet
    restart: always
    volumes:
      - ./wireguard-ui/data:/app/db
      - ./wireguard/config:/etc/wireguard

networks:
  wgnet:
    driver: bridge
